packages:
  - .
  - playgrounds/*

ignoreWorkspaceRootCheck: true
linkWorkspacePackages: true

allowBuilds:
  esbuild: true
  vue-demi: true

overrides:
  tailwind-variants: 3.2.2

catalog:
  "@nuxt/kit": ^4.5.2
  "@nuxt/module-builder": ^1.0.3
  "@storybook/addon-docs": ^10.6.0
  "@storybook/addon-themes": ^10.6.0
  "@storybook/vue3-vite": ^10.6.0
  "@nuxt/schema": ^4.5.2
  "@nuxtjs/storybook": 9.1.0-29411911.f34c865
  "@storybook-vue/nuxt": 9.1.0-29411911.f34c865
  "@tailwindcss/vite": ^4.3.3
  "@types/node": ^24.5.2
  "@vitejs/plugin-vue": ^6.0.9
  "@vue/test-utils": ^2.4.6
  defu: ^6.1.4
  eslint: ^9.36.0
  eslint-plugin-vue: ^10.5.0
  happy-dom: ^20.0.0
  nuxt: ^4.5.2
  storybook: ^10.6.0
  storybook-addon-pseudo-states: ^10.6.0
  reka-ui: ^2.5.0
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.3.3
  typescript: ^5.9.2
  typescript-eslint: ^8.44.0
  unbuild: ^3.6.1
  unplugin: ^2.3.10
  unplugin-auto-import: ^20.2.0
  unplugin-vue-components: ^29.1.0
  vite: ^7.1.5
  vitest: ^3.2.4
  vitest-axe: ^0.1.0
  vue: ^3.5.22
  vue-tsc: ^3.0.7
